// Converts Dart objects into JSON and converts JSON responses back into
// Dart objects. This is required for sending and receiving API data.
import 'dart:convert';

// Provides HTTP methods such as GET and POST.
// This package is used to send the request to the Groq API.
import 'package:http/http.dart' as http;

// Imports the application configuration file.
// AppConfig stores and validates the Groq API key.
import '../core/app_config.dart';

/// Represents one message inside the AI assistant conversation.
///
/// Each message contains:
/// - The actual message text
/// - A Boolean value indicating whether the message came from the user
class ChatMessage {
  /// Stores the content of the chat message.
  final String text;

  /// Identifies who sent the message.
  ///
  /// true means the message was sent by the user.
  /// false means the message was generated by the AI assistant.
  final bool isUser;

  /// Constructor used to create a ChatMessage object.
  ///
  /// Both values are required because every message must contain text
  /// and must identify whether it came from the user or the assistant.
  ChatMessage({
    required this.text,
    required this.isUser,
  });
}

/// Represents one Groq AI model that the user can select.
///
/// Only selected free-tier models are provided to reduce the chance of
/// exceeding stricter usage and rate limits.
class GroqModelOption {
  /// Stores the technical model identifier expected by the Groq API.
  ///
  /// Example:
  /// llama-3.3-70b-versatile
  final String id;

  /// Stores the user-friendly model name displayed in the application.
  ///
  /// Example:
  /// Llama 3.3 70B
  final String label;

  /// Constant constructor used because the available model information
  /// does not change while the application is running.
  const GroqModelOption({
    required this.id,
    required this.label,
  });
}

/// Handles communication between the Expense Analyzer application
/// and the Groq artificial-intelligence API.
///
/// This service is responsible for:
/// - Preparing the financial-assistant system prompt
/// - Adding previous conversation history
/// - Sending requests to Groq
/// - Handling API errors
/// - Extracting the generated response
class GroqService {
  /// The Groq chat-completions API endpoint.
  ///
  /// Groq uses an OpenAI-compatible request structure, which means
  /// the request contains roles such as system, user and assistant.
  static const String _endpoint =
      'https://api.groq.com/openai/v1/chat/completions';

  /// List of AI models available for selection in the application.
  ///
  /// The models appear in this same order in the user interface.
  /// The first model is treated as the preferred default model.
  static const List<GroqModelOption> availableModels = [
    /// Larger model intended to provide more detailed and capable answers.
    GroqModelOption(
      id: 'llama-3.3-70b-versatile',
      label: 'Llama 3.3 70B',
    ),

    /// Smaller and faster model intended for quick responses.
    GroqModelOption(
      id: 'llama-3.1-8b-instant',
      label: 'Llama 3.1 8B Instant',
    ),

    /// Alternative instruction-following model available through Groq.
    GroqModelOption(
      id: 'gemma2-9b-it',
      label: 'Gemma2 9B',
    ),
  ];

  /// Defines the model that will be used when the user has not selected
  /// another model.
  static const String defaultModel = 'llama-3.3-70b-versatile';

  /// Creates the system prompt that controls the AI assistant's behaviour.
  ///
  /// The method receives financialContext, which contains the user's
  /// calculated financial information, such as expenses, income and budget.
  ///
  /// The arrow syntax returns the multi-line string directly.
  String _systemPrompt(String financialContext) => '''
You are "Fin", a friendly and concise personal-finance assistant built into an
expense-tracking app. Answer questions about the user's spending, income,
budget and savings using ONLY the data provided below. Be specific and cite
real numbers from the data. If the user asks something the data cannot answer,
say so briefly and offer general guidance. Keep answers short (a few sentences),
use the user's currency symbol (\$), and be encouraging.

=== USER FINANCIAL DATA ===
$financialContext
=== END DATA ===
''';

  /// Sends a new user message to the Groq API and returns the AI response.
  ///
  /// Required inputs:
  /// - financialContext: Financial data supplied to the assistant
  /// - history: Previous user and assistant messages
  /// - message: The user's latest question
  ///
  /// modelName is optional. When no model is provided, defaultModel is used.
  Future<String> sendMessage({
    required String financialContext,
    required List<ChatMessage> history,
    required String message,
    String modelName = defaultModel,
  }) async {
    /// Verifies that a Groq API key has been configured before attempting
    /// to send the network request.
    ///
    /// This prevents the application from sending an unauthorized request
    /// when the required API key is missing.
    if (!AppConfig.isGroqConfigured) {
      throw Exception(
        'Groq API key not configured. Set GROQ_API_KEY via --dart-define '
        'or edit lib/core/app_config.dart.',
      );
    }

    /// Builds the conversation in the OpenAI-compatible chat format.
    ///
    /// The messages must appear in the correct order:
    /// 1. System instructions and financial context
    /// 2. Previous conversation history
    /// 3. The user's newest message
    final messages = <Map<String, String>>[
      /// The system message defines the assistant's role, restrictions
      /// and access to the user's financial context.
      {
        'role': 'system',
        'content': _systemPrompt(financialContext),
      },

      /// Converts every previous ChatMessage into the role-based structure
      /// required by the Groq API.
      ///
      /// A user message receives the "user" role.
      /// An AI-generated message receives the "assistant" role.
      for (final m in history)
        {
          'role': m.isUser ? 'user' : 'assistant',
          'content': m.text,
        },

      /// Adds the user's newest message after all previous conversation turns.
      {
        'role': 'user',
        'content': message,
      },
    ];

    /// Sends an HTTP POST request to the Groq API.
    ///
    /// POST is used because the application is sending conversation data
    /// and requesting a newly generated response.
    final response = await http
        .post(
          /// Converts the endpoint string into a Uri object accepted
          /// by the HTTP package.
          Uri.parse(_endpoint),

          /// HTTP headers provide authentication and describe the body format.
          headers: {
            /// Sends the API key using Bearer-token authentication.
            'Authorization': 'Bearer ${AppConfig.groqApiKey}',

            /// Informs the API that the request body contains JSON.
            'Content-Type': 'application/json',
          },

          /// Converts the Dart map into a JSON string.
          ///
          /// The request includes:
          /// - The selected AI model
          /// - The complete message list
          body: jsonEncode({
            'model': modelName,
            'messages': messages,
          }),
        )

        /// Stops waiting if Groq does not respond within 30 seconds.
        ///
        /// This prevents the application from remaining stuck indefinitely
        /// because of a slow or unavailable network connection.
        .timeout(const Duration(seconds: 30));

    /// Checks whether Groq returned a successful HTTP response.
    ///
    /// HTTP status code 200 indicates that the request was processed
    /// successfully.
    if (response.statusCode != 200) {
      /// Throws an exception containing both the status code and response body.
      ///
      /// This information helps identify problems such as:
      /// - Invalid API key
      /// - Invalid model
      /// - Rate-limit errors
      /// - Incorrect request format
      throw Exception(
        'Groq request failed (${response.statusCode}): ${response.body}',
      );
    }

    /// Converts the JSON response string into a Dart map.
    final data = jsonDecode(response.body) as Map<String, dynamic>;

    /// Retrieves the choices array from the API response.
    ///
    /// Groq normally places generated answers inside this list.
    /// The nullable type is used because the field could be missing.
    final choices = data['choices'] as List<dynamic>?;

    /// Extracts the assistant's reply from the first generated choice.
    ///
    /// The condition verifies that:
    /// - choices is not null
    /// - choices contains at least one item
    ///
    /// The null-aware operators prevent crashes if any expected field
    /// is missing from the response.
    final reply =
        (choices != null && choices.isNotEmpty)
            ? (choices.first['message']?['content'] as String?)?.trim()
            : null;

    /// Returns the generated AI reply when it is valid and not empty.
    ///
    /// If Groq returns no usable text, the application provides a
    /// user-friendly fallback message instead of showing a blank response.
    return reply != null && reply.isNotEmpty
        ? reply
        : "Sorry, I couldn't generate a response. Please try again.";
  }
}
