import 'package:supabase_flutter/supabase_flutter.dart';
import '../models/transaction_model.dart';
import '../models/budget_model.dart';

/// TransactionService acts as the main data-access layer for the application.
///
/// It connects the Flutter application to Supabase and manages:
/// 1. Transaction creation, retrieval, updating and deletion
/// 2. Monthly income and expense analytics
/// 3. Budget retrieval and storage
///
/// Keeping this logic inside a separate service makes the application
/// easier to maintain because database operations are not mixed with UI code.
class TransactionService {
  /// Creates a reusable reference to the initialized Supabase client.
  ///
  /// This client is used for all communication with the Supabase database.
  final SupabaseClient _client = Supabase.instance.client;

  // ---------------------------------------------------------------------------
  // TRANSACTION RETRIEVAL
  // ---------------------------------------------------------------------------

  /// Retrieves all transactions belonging to a specific user.
  ///
  /// The user ID is included in the query so that each user only receives
  /// their own financial records.
  Future<List<Transaction>> getTransactions(String userId) async {
    final data = await _client
        // Select data from the transactions table.
        .from('transactions')

        // Retrieve all columns from the matching records.
        .select()

        // Filter the results using the authenticated user's ID.
        .eq('user_id', userId)

        // Display the newest transactions first.
        .order('date', ascending: false);

    /// Supabase returns the result as raw JSON-like maps.
    ///
    /// Each database row is converted into a Transaction object so that
    /// the rest of the Flutter application can work with strongly typed data.
    return (data as List)
        .map(
          (row) =>
              Transaction.fromJson(row as Map<String, dynamic>),
        )
        .toList();
  }

  // ---------------------------------------------------------------------------
  // ADD TRANSACTION
  // ---------------------------------------------------------------------------

  /// Adds a new income or expense transaction to Supabase.
  ///
  /// The method receives a Transaction object and the current user's ID.
  Future<Transaction> addTransaction(
    Transaction transaction,
    String userId,
  ) async {
    /// Creates the database payload.
    ///
    /// The spread operator copies all transaction fields from toJson(),
    /// while user_id is added separately to link the record to its owner.
    final payload = {
      ...transaction.toJson(),
      'user_id': userId,
    };

    /// Inserts the transaction into Supabase.
    ///
    /// select().single() returns the exact record that was created,
    /// including any values generated by the database, such as its ID.
    final row = await _client
        .from('transactions')
        .insert(payload)
        .select()
        .single();

    /// Converts the returned database row into a Transaction model.
    return Transaction.fromJson(row);
  }

  // ---------------------------------------------------------------------------
  // UPDATE TRANSACTION
  // ---------------------------------------------------------------------------

  /// Updates an existing transaction.
  ///
  /// The transaction ID is used to locate the correct database record.
  Future<Transaction> updateTransaction(
    Transaction transaction,
  ) async {
    final row = await _client
        .from('transactions')

        // Convert the updated Transaction object into database-ready JSON.
        .update(transaction.toJson())

        // Update only the row that matches this transaction ID.
        .eq('id', transaction.id)

        // Return the updated row after the database operation completes.
        .select()
        .single();

    return Transaction.fromJson(row);
  }

  // ---------------------------------------------------------------------------
  // DELETE TRANSACTION
  // ---------------------------------------------------------------------------

  /// Deletes a transaction using its unique ID.
  ///
  /// This was an important feature because the UI must also refresh after
  /// the database record is removed.
  Future<void> deleteTransaction(String id) async {
    await _client
        .from('transactions')
        .delete()
        .eq('id', id);
  }

  // ---------------------------------------------------------------------------
  // MONTHLY ANALYTICS
  // ---------------------------------------------------------------------------

  /// Calculates financial analytics for one selected month.
  ///
  /// This method replaced the previous Java backend analytics endpoint.
  /// The analytics are now calculated directly using data from Supabase.
  ///
  /// The expected month format is YYYY-MM, for example: 2026-07.
  Future<Map<String, dynamic>> getAnalytics(
    String userId,
    String month,
  ) async {
    /// Splits the month into its year and month components.
    ///
    /// For example, "2026-07" becomes ["2026", "07"].
    final parts = month.split('-');

    final year = int.parse(parts[0]);
    final mon = int.parse(parts[1]);

    /// Creates the first date of the requested month.
    final start = DateTime(year, mon, 1);

    /// Using day zero of the next month automatically returns
    /// the final day of the current month.
    ///
    /// This also handles months containing 28, 29, 30 or 31 days.
    final end = DateTime(year, mon + 1, 0);

    /// Formats Dart DateTime values into the YYYY-MM-DD format
    /// expected by the Supabase date column.
    String fmt(DateTime d) =>
        '${d.year.toString().padLeft(4, '0')}-'
        '${d.month.toString().padLeft(2, '0')}-'
        '${d.day.toString().padLeft(2, '0')}';

    /// Retrieves only the selected user's transactions
    /// that fall within the chosen month.
    final data = await _client
        .from('transactions')
        .select()
        .eq('user_id', userId)
        .gte('date', fmt(start))
        .lte('date', fmt(end));

    /// Variables used to calculate the summary values.
    double totalIncome = 0;
    double totalExpense = 0;

    /// Stores total expenses grouped by category.
    ///
    /// Example:
    /// {
    ///   "Food": 350.00,
    ///   "Transportation": 120.00
    /// }
    final Map<String, double> categoryBreakdown = {};

    /// Stores total expenses grouped by date.
    ///
    /// This information can be used for daily spending charts.
    final Map<String, double> dailyBreakdown = {};

    /// Processes every transaction returned from Supabase.
    for (final row in (data as List)) {
      final map = row as Map<String, dynamic>;

      /// Converts the transaction type to lowercase so that the comparison
      /// still works even if capitalization differs.
      final type =
          (map['type'] ?? '').toString().toLowerCase();

      /// Converts the database amount into a Dart double.
      final amount = (map['amount'] as num).toDouble();

      final day = map['date'].toString();

      /// Uses "Other" as a safe fallback when no category exists.
      final category =
          (map['category'] ?? 'Other').toString();

      if (type == 'income') {
        /// Income transactions increase total income.
        totalIncome += amount;
      } else {
        /// All non-income transactions are treated as expenses.
        totalExpense += amount;

        /// Adds the expense to its category total.
        ///
        /// If the category already exists, its value is increased.
        /// Otherwise, a new category entry is created.
        categoryBreakdown.update(
          category,
          (currentValue) => currentValue + amount,
          ifAbsent: () => amount,
        );

        /// Adds the expense to the corresponding daily total.
        dailyBreakdown.update(
          day,
          (currentValue) => currentValue + amount,
          ifAbsent: () => amount,
        );
      }
    }

    /// Retrieves the monthly budget after calculating the transaction totals.
    final budget = await getBudget(userId, month);

    /// When no budget exists, the application safely uses zero.
    final budgetLimit = budget?.amount ?? 0.0;

    /// Returns all calculated information in one structured map.
    ///
    /// The UI can use these values for dashboard cards, charts,
    /// category analysis and budget progress indicators.
    return {
      'totalIncome': totalIncome,
      'totalExpense': totalExpense,

      // Current balance after subtracting expenses from income.
      'balance': totalIncome - totalExpense,

      'budgetLimit': budgetLimit,

      /// Prevents division by zero when a user has not created a budget.
      'budgetPercentage':
          budgetLimit > 0
              ? (totalExpense / budgetLimit) * 100
              : 0.0,

      'categoryBreakdown': categoryBreakdown,
      'dailyBreakdown': dailyBreakdown,
    };
  }

  // ---------------------------------------------------------------------------
  // BUDGET RETRIEVAL
  // ---------------------------------------------------------------------------

  /// Retrieves a user's budget for a particular month.
  Future<Budget?> getBudget(
    String userId,
    String month,
  ) async {
    final row = await _client
        .from('budgets')
        .select()

        // Identify the owner of the budget.
        .eq('user_id', userId)

        // Retrieve the budget for the selected month.
        .eq('month', month)

        /// maybeSingle() is used because a budget may not exist yet.
        ///
        /// Unlike single(), this does not fail when no matching row is found.
        .maybeSingle();

    /// Return null when the user has not created a budget.
    if (row == null) return null;

    return Budget.fromJson(row);
  }

  // ---------------------------------------------------------------------------
  // CREATE OR UPDATE BUDGET
  // ---------------------------------------------------------------------------

  /// Creates a new monthly budget or updates an existing one.
  Future<Budget> setBudget(
    String userId,
    double amount,
    String month,
  ) async {
    final row = await _client
        .from('budgets')

        /// Upsert combines insert and update functionality.
        ///
        /// If a budget for the same user and month already exists,
        /// Supabase updates it instead of creating a duplicate record.
        .upsert(
          {
            'user_id': userId,
            'amount': amount,
            'month': month,
          },

          /// The combination of user_id and month uniquely identifies
          /// one monthly budget.
          onConflict: 'user_id,month',
        )

        // Return the inserted or updated budget record.
        .select()
        .single();

    return Budget.fromJson(row);
  }
}
